name: mobile_flutter
description: "心理健康智能系统 Android 客户端。"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.13.0

dependencies:
  audioplayers: 6.8.1
  crypto: ^3.0.7
  dio: ^5.11.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_local_notifications: 22.3.0
  flutter_riverpod: ^2.6.1
  flutter_secure_storage: 10.3.1
  flutter_timezone: ^5.1.0
  flutter_tts: ^4.2.5
  flutter_webrtc: 1.6.0
  go_router: ^17.5.0
  permission_handler: 12.0.1
  signalr_netcore: 1.4.4
  timezone: ^0.11.1
  webview_flutter: 4.14.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/audio/fallback-chime.wav
    - assets/certs/demo_root.crt
    - assets/images/login-room.webp
    - assets/images/empty-room.webp
