name: mobile_flutter
description: "心理健康智能系统 Android 客户端。"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.13.0

dependencies:
  flutter:
    sdk: flutter
  flutter_tts: ^4.2.5
  flutter_webrtc: 1.6.0
  signalr_netcore: 1.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
