name: mobile_flutter
description: "心理健康智能系统 Android 客户端。"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.13.0

dependencies:
  crypto: ^3.0.7
  dio: ^5.11.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_secure_storage: 10.3.1
  flutter_tts: ^4.2.5
  flutter_webrtc: 1.6.0
  go_router: ^17.5.0
  permission_handler: 12.0.1
  signalr_netcore: 1.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/certs/demo_root.crt
